# Generated by Django 5.2.10 on 2026-01-25 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_dailycalories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
