# Generated by Django 5.2.10 on 2026-02-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_dailycalories_carbs_consumed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycalories',
            name='carbs_consumed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='dailycalories',
            name='fats_consumed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='dailycalories',
            name='protein_consumed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
    ]
