# Generated by Django 5.2.10 on 2026-02-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_dailycalories_carbs_consumed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='dietary_tags',
        ),
        migrations.AddField(
            model_name='recipe',
            name='dietary_tag',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
